version: "3.9"

services:
  app:
    build: .
    container_name: pixel-canvas
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev -- --host 0.0.0.0
